dist: trusty
sudo: required
services: 
  - docker
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
language: node.js
node_js:
  - '8'
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq docker-ce
  - curl -o- -L http://yarnpkg.com/install.sh | bash
cache:
  yarn: true
install: yarn install
script:
  - bash ./deploy/deploy.sh